[versions]
agp = "8.13.0"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"
roomRuntime = "2.8.3"
coreKtxVersion = "1.9.0"
appcompatVersion = "1.6.1"
materialVersion = "1.10.0"
constraintlayoutVersion = "2.1.4"
x_androidxCoreKtx = "1.9.0"
x_androidxAppcompat = "1.6.1"
x_comMaterial = "1.10.0"
x_androidxConstraintlayout = "2.1.4"
recyclerview = "1.4.0"
x_androidxCoreKtxVersion = "1.13.1"
recyclerviewVersion = "1.3.2"
roomKtx = "$room_version"
androidxRecyclerview = "1.3.0"
roomKtxVersion = "$room_version"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
core-ktx = { group = "(", name = "core-ktx", version.ref = "coreKtxVersion" }
appcompat = { group = "(", name = "appcompat", version.ref = "appcompatVersion" }
x_com-material = { group = "(", name = "material", version.ref = "materialVersion" }
constraintlayout = { group = "(", name = "constraintlayout", version.ref = "constraintlayoutVersion" }
x_androidx-core-ktx = { group = "(", name = "core-ktx", version.ref = "x_androidxCoreKtx" }
x_androidx-appcompat = { group = "(", name = "appcompat", version.ref = "x_androidxAppcompat" }
x_com-google-android-material-material = { group = "(", name = "material", version.ref = "x_comMaterial" }
x_androidx-constraintlayout = { group = "(", name = "constraintlayout", version.ref = "x_androidxConstraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
x_androidx-core-core-ktx = { group = "(", name = "core-ktx", version.ref = "x_androidxCoreKtxVersion" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerviewVersion" }
room-ktx = { group = "(", name = "room-ktx", version.ref = "roomKtx" }
androidx-recyclerview-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerview" }
x_androidx-room-ktx = { group = "(", name = "room-ktx", version.ref = "roomKtxVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

